### ISSUE TITLE
你好,我想知道fad文件是如何编辑的

### ISSUE THREAD

**Issue by imjinjia** [wmltogether/yomawari-pc-translation#1]
有没有工具呢？实在是搞不懂。

**Comment by wmltogether** [comment]
没遇到过这种扩展名的数据格式

**Comment by imjinjia** [comment]
夜廻是你们汉化的吧，里面的UI图是fad后缀。

**Comment by imjinjia** [comment]
需要大神技术支持。

**Comment by imjinjia** [comment]
其实我是想移植pc深夜廻汉化版到psv，无奈搞不明白里面的UI图。

**Comment by wmltogether** [comment]
一代好像是TGA图来着

**Comment by imjinjia** [comment]
能拜托看一下2代么，貌似一样的。

**Comment by wmltogether** [comment]
感觉就是个普通的包吧，里面还是tga，有一部分是lzss压缩过的
索引是
struct 
{
    file_name 8bytes string
    file_size uint32
    file_type uint32
    file_offset uint32
    null uint32
    null uint32
    null uint32
}

**Comment by imjinjia** [comment]
像我这种小白对这类东西感到非常无力，除非大神做个工具、脚本啥的。。。

**Comment by wmltogether** [comment]
已不做汉化好多年，懒得写工具了，你自己写一下吧，挺简单的
